name: qt-deployer
version: '1.1.1'
summary: Deploy Qt Project
description: |
  Deploy Qt Projects. this application extract all depends library of executable and create launch script for your application. |
  All you need is to select a folder with a compiled libraries of qt and a folder with your project.
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots


icon: snap/gui/icon.png

apps:
  qt-deployer:
    command: desktop-launch $SNAP/opt/qt-deployer/bin/qt-deployer
#    desktop: usr/share/applications/desc.desktop
    plugs: [desktop, home, opengl, x11, wayland, removable-media, gsettings, dbus, unity7]


parts:
  qt-deployer:
    plugin: qmake
    source: source/
    build-packages:
      - qtbase5-dev
    stage-packages:
      # Here for the plugins-- they're not linked in automatically.
      - libqt5gui5
      - libc6-dev
    after: [desktop-qt5] # A wiki part
